- name: Install packages
  become: True
  community.general.pacman:
    name: "{{ postgres_arch_packages }}"

- name: Make sure the postgres users home is set to our root path
  become: true
  ansible.builtin.user:
    name: "{{ postgresql_user }}"
    home: "{{ postgresql_root_path }}"
    append: yesschema_name

- name: Check if DB already initialized
  become: true
  ansible.builtin.stat:
    path: "{{ postgresql_data_path }}"
  register: postgresql_path_present

- name: Ensure the data path exists
  become: true
  ansible.builtin.file:
    state: directory
    path: "{{ postgresql_root_path }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_user }}"
  loop:
    - "{{ postgresql_root_path }}"
    - "{{ postgresql_data_path }}"
    - "{{ postgresql_config_path }}"
    - "{{ postgresql_config_path }}/conf.d"
  loop_control:
    loop_var: postgresql_path

- name: Initialize the Postgres cluster
  become: True
  when: not postgresql_path_present.stat.exists
  ansible.builtin.shell:
    cmd: >
      sudo -u postgres initdb -D {{ postgresql_data_path }}

- name: Create replacement SystemD service
  become: True
  ansible.builtin.template:
    src: Archlinux_systemd.service.j2
    dest: /usr/lib/systemd/system/postgresql.service

- name: Render configuration files
  become: True
  template:
    src: "postgresql.conf.j2"
    dest: "{{ postgresql_config_path }}/postgresql.conf"

- name: Restart PostgreSQL service
  become: True
  service:
    daemon_reload: true
    name: postgresql
    state: restarted
    enabled: True
