- name: Collect Distribution specific host vars for local usage
  set_fact:
    postgresql_config_path: "{{ hostvars[inventory_hostname].postgresql_config_path }}"
    postgresql_root_path: "{{ hostvars[inventory_hostname].postgresql_root_path }}"
    postgresql_version:  "{{ hostvars[inventory_hostname].postgresql_version }}"

- name: Install packages
  become: True
  apt:
    name: "{{ postgresql_debian_packages }}"
      
- name: Start postgresql service
  become: True
  service:
    name: postgresql
    state: started

- name: Render configuration files
  become: True
  template:
    src: "postgresql-{{ postgresql_version }}.conf.j2"
    dest: "{{ postgresql_config_path }}/postgresql.conf"

- name: Restart PostgreSQL service
  become: True
  service:
    name: postgresql
    state: restarted
    enabled: True
