---
- name: Set some variables as facts for use outside role
  set_fact:
    postgresql_password_encryption: "{{ postgresql_password_encryption }}"
    postgresql_version: "{{ postgresql_version }}"
    postgresql_port: "{{ postgresql_port }}"

# The file is split like this for variable merging from role
- name: common | Super
  when: is_super | bool
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_os_family }}_{{ ansible_architecture }}_super.yml"
      - "{{ ansible_os_family }}_super.yml"
      skip: True