---
- name: developer | Install packages
  become: true
  community.general.pacman:
    name: "{{ developer_arch_packages }}"

- name: developer | Install AUR packages if helper enabled
  when:
    - yay_install
  kewlfft.aur.aur:
    name: "{{ developer_arch_aur_packages }}"
    state: present
  become: yes
  become_user: "{{ aur_build_user }}"
