jenkins_java_version: 17

jenkins_arch_packages:
  - fontconfig
  - freetype2
  - "jre{{ jenkins_java_version }}-openjdk-headless"
  - jenkins

jenkins_cli_package_url: jnlpJars/jenkins-cli.jar

jenkins_debian_packages:
  - "openjdk-{{ jenkins_java_version }}-jre-headless"
  - jenkins

jenkins_reference: jenkins
jenkins_port: 8080

jenkins_user: jenkins
jenkins_user_group: "{{ jenkins_user }}"
jenkins_home: /var/lib/jenkins
jenkins_unpacked_path: /var/cache/jenkins/war
jenkins_admin_user_name: admin
jenkins_admin_user_pass: development
jenkins_admin_email: not@applicable.com

jenkins_plugins:
  - "docker-workflow"
  - "javax-mail-api"
  - "plain-credentials"
  - "pipeline-model-api"
  - "workflow-support"
  - "cloudbees-folder"
  - "antisamy-markup-formatter"
  - "okhttp-api"
  - "variant"
  - "pipeline-groovy-lib"
  - "mailer"
  - "pipeline-input-step"
  - "pipeline-stage-step"
  - "branch-api"
  - "javax-activation-api"
  - "echarts-api"
  - "ws-cleanup"
  - "build-timeout"
  - "pipeline-model-extensions"
  - "workflow-cps"
  - "ssh-credentials"
  - "checks-api"
  - "instance-identity"
  - "pipeline-milestone-step"
  - "scm-api"
  - "credentials-binding"
  - "workflow-api"
  - "ionicons-api"
  - "workflow-job"
  - "font-awesome-api"
  - "trilead-api"
  - "matrix-project"
  - "script-security"
  - "commons-lang3-api"
  - "ldap"
  - "workflow-step-api"
  - "jaxb"
  - "pipeline-rest-api"
  - "jakarta-activation-api"
  - "mina-sshd-api-common"
  - "workflow-aggregator"
  - "sshd"
  - "timestamper"
  - "docker-commons"
  - "durable-task"
  - "git"
  - "plugin-util-api"
  - "workflow-multibranch"
  - "display-url-api"
  - "commons-text-api"
  - "apache-httpcomponents-client-4-api"
  - "workflow-scm-step"
  - "pipeline-model-definition"
  - "mina-sshd-api-core"
  - "jjwt-api"
  - "pipeline-stage-tags-metadata"
  - "pipeline-graph-analysis"
  - "bootstrap5-api"
  - "pipeline-stage-view"
  - "snakeyaml-api"
  - "pam-auth"
  - "authentication-tokens"
  - "ssh-slaves"
  - "credentials"
  - "jquery3-api"
  - "pipeline-build-step"
  - "pipeline-github-lib"
  - "resource-disposer"
  - "generic-webhook-trigger"
  - "junit"
  - "workflow-durable-task-step"
  - "matrix-auth"
  - "git-client"
  - "jakarta-mail-api"
  - "jackson2-api"
  - "workflow-basic-steps"
  - "structs"
  - "caffeine-api"
  - "bouncycastle-api"
  - "token-macro"
