---
- name: desktop | Super
  when:
    - is_super | bool
    - not include_only_deployed_apps
    - include_desktop_management
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}_{{ ansible_architecture }}_super.yml"
        - "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}_super.yml"
        - "{{ ansible_os_family }}_{{ ansible_architecture }}_super.yml"
        - "{{ ansible_os_family }}_super.yml"
      skip: True


