- name: Variable fallback
  set_fact:
    certificate_authority_cert_format: "{{ hostvars[groups['certificate_authority'][0]]['certificate_authority_cert_format'] }}"

- name: Copy certificate to host - Arch Linux
  become: true
  when: ansible_os_family == "Archlinux"
  ansible.builtin.copy:
    src: "{{ ansible_working_path }}/ca-chain.cert.{{ certificate_authority_cert_format }}"
    dest: "{{ common_user_home }}/ca-chain.cert.{{ certificate_authority_cert_format }}"

- name: Run trust agent
  become: true
  when: ansible_os_family == "Archlinux"
  ansible.builtin.shell: >-
    trust anchor --store {{ common_user_home }}/ca-chain.cert.{{ certificate_authority_cert_format }}

- name: Ensure cert path exists
  become: true
  when: ansible_os_family == "Debian"
  file:
    path: /usr/local/share/certificates
    state: directory

- name: Copy certificate to host - Debian / Ubuntu Linux
  become: true
  when: ansible_os_family == "Debian"
  ansible.builtin.copy:
    src: "{{ ansible_working_path }}/ca-chain.cert.{{ certificate_authority_cert_format }}"
    dest: "/usr/local/share/certificates/{{ ansible_project_name }}-ca-chain.crt"

- name: Run trust agent
  become: true
  when: ansible_os_family == "Debian"
  ansible.builtin.shell: >-
    update-ca-certificates