---
- name: install_aur_packages | Install AUR packages
  become: true
  become_user: "{{ aur_build_user }}"
  ansible.builtin.command:
    cmd: >
      yay -S --noconfirm --nodiffmenu --nocleanmenu {{ aur_package }}
#  register: aur_output
#  changed_when: "'Running post-transaction hooks' in aur_output.stdout"
  loop: "{{ aur_packages }}"
  loop_control:
    loop_var: aur_package
