---
- name: super | Install base requirements for Conda
  become: true
  community.general.pacman:
    name:
      - python-pycosat
      - python-tqdm
      - python-libarchive-c

- name: packages | Install AUR packages if helper enabled
  ansible.builtin.import_tasks: tasks/install_aur_packages.yml
  when: yay_install
  vars:
    aur_packages:
      - python-conda-package-handling