---
mariadb_data_dir: /var/lib/mysql
mariadb_collation_server: utf8mb4_unicode_ci
mariadb_chatacter_set: utf8mb4
mariadb_bind_address: localhost
mariadb_skip_networking: true
mariadb_user: mysql
mariadb_group: mysql

mariadb_packages:
  - mariadb
