---
# The file is split like this for variable merging from role
- debug: msg="{{ ansible_os_family }}_{{ ansible_architecture }}_super.yml"
- name: common | Super
  when:
    - is_super | bool
    - include_mariadb_management
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}_{{ ansible_architecture }}_super.yml"
        - "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}_super.yml"
        - "{{ ansible_os_family }}_{{ ansible_architecture }}_super.yml"
        - "{{ ansible_os_family }}_super.yml"
      skip: True
