- name: Define reverse proxy rule
  import_tasks: define_proxy.yml

- name: Install
  become: True
  community.general.pacman:
    name: "{{ jenkins_arch_packages }}"

- name: Create config
  become: True
  ansible.builtin.template:
    src: Archlinux_conf.d_jenkins.j2
    dest: /etc/conf.d/jenkins

- name: Add jenkins to the docker group
  when: "'docker' in group_names"
  become: True
  user:
    name: "{{ jenkins_user }}"
    append: true
    groups: docker

- name: Enable Jenkins Service
  become: True
  ansible.builtin.systemd:
    name: jenkins
    state: started
    enabled: yes

- name: Post install setup
  import_tasks: post_install.yml