- name: Create Nginx rule
  import_tasks: tasks/nginx_reverse_proxy.yml
  vars:
    reference: "{{ role_name }}"
    app_port: "{{ jenkins_port }}"
    letsencrypt: "{{ nginx_facade_use_certbot }}"
    domain: "{{ jenkins_fqcdn }}"
    proxy_extra_root_rules: |
      # WebSocket rules
      map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
      }
    proxy_extra_location_rules: |
      # Disable Nginx buffering for CLI / integrations 
      proxy_request_buffering off;
      proxy_buffering off;
      # WebSocket rules
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
    proxy_extra_server_rules: |
      # pass through headers from Jenkins that Nginx considers invalid
      ignore_invalid_headers off;