# The file is split like this for variable merging from role
- name: nginx | Super
  when: is_super | bool
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_os_family }}_{{ ansible_architecture }}_super.yml"
      - "{{ ansible_os_family }}_super.yml"
      skip: True