---
- name: virtualbox | Install packages
  become: true
  community.general.pacman:
    name: "{{ arch_linux_virtualbox_packages }}"

- name: packages | Install AUR packages
  when:
    - yay_install
  kewlfft.aur.aur:
    name: "{{ arch_linux_virtualbox_aur_packages }}"
    state: present
  become: yes
  become_user: "{{ aur_build_user }}"

- name: virtualbox | Add the user to the vboxusers user group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_ssh_user }}"
    groups: vboxusers
    append: true
