- name: GoLang installed
  become: True
  apt:
    name: "{{ go_debian_packages }}"

- name: Update paths for golang
  become: True
  ansible.builtin.copy:
    src: golang_path.sh
    dest: /etc/profile.d/golang_path.sh
