- name: Add Example GPG key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /etc/apt/keyrings/hashicorp.asc
    mode: '0644'
    force: true

- name: Debian_docker | Add VSCode APT repository
  become: True
  apt_repository:
    repo: >-
      deb
      [signed-by=/etc/apt/keyrings/hashicorp.gpg]
      https://apt.releases.hashicorp.com jammy main
    state: present
    filename: hashicorp