- name: Make sure working directory
  become: True
  file:
    state: directory
    owner: "{{ common_user }}"
    group: "{{ common_group }}"
    path: "{{ common_working_path }}/terraform"

- name: "Add GPG key for Terraform from {{ terraform_repository_key_path }}"
  become: True
  apt_key: "url={{ terraform_repository_key_path }}"

- name: "add repo for Terraform"
  apt_repository:
    repo: "deb [arch=amd64] {{ terraform_repository_base_url }} stable main"
    update_cache: yes

- name: install Terraform
  apt:
    name: terraform
