postgresql_arch_packages:
  - postgresql
postgresql_arch_version: 16
postgresql_arch_root_path: /var/lib/postgres/data
postgresql_arch_config_path: "{{ postgresql_arch_root_path }}"

postgresql_debian_packages:
  - postgresql
  - postgresql-client
  - postgresql-contrib

postgresql_debian_11_version: 13
postgresql_debian_11_root_path: "/var/lib/postgresql/{{ postgresql_debian_11_version }}/main"
postgresql_debian_11_config_path: "/etc/postgresql/{{ postgresql_debian_11_version }}/main"

postgresql_debian_22_version: 14
postgresql_debian_22_root_path: "/var/lib/postgresql/{{ postgresql_debian_22_version }}/main"
postgresql_debian_22_config_path: "/etc/postgresql/{{ postgresql_debian_22_version }}/main"


postgresql_port: 5432
postgresql_user: postgres
postgresql_listen_address: '*'

postgresql_socket_path: "/var/run/postgresql"
postgresql_max_connections: 100
postgresql_password_encryption: scram-sha-256

# Minimum 128KB
postgresql_shared_buffer_size: 128MB
# on, off, try
postgresql_huge_pages: try
# Minimum 800KB
postgresql_temp_buffer_size: 8MB
postgresql_max_prepared_transactions: 0

